services:
  # PostgreSQL Database
  db:
    image: postgres:15-alpine
    container_name: postgres-db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  # Redis Cache
  redis:
    image: redis:7-alpine
    container_name: redis-cache
    ports:
      - "6379:6379"

  # API Server
  api-server:
    build: ./api-server
    container_name: api-server
    ports:
      - "${PORT}:5000"
    env_file:
      - .env
    depends_on:
      - db
      - redis
    volumes:
      - ./api-server/src:/app/src
      - ./api-server/prisma:/app/prisma

  # ML Service
  ml-service:
    build: ./artist-ml-service
    container_name: artist-ml-service
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./artist-ml-service/app:/app/app

volumes:
  db_data: