from dotenv import load_dotenv
import os

load_dotenv()

# Constants for the application
GEMINI_AI_STUDIO_API_KEY = os.getenv('GEMINI_AI_STUDIO_API_KEY')
GEMINI_GCP_API_KEY = os.getenv('GEMINI_GCP_API_KEY')
GCP_PROJECT_ID = os.getenv('GCP_PROJECT_ID')
PROFILE_GENERATION_ENDPOINT = os.getenv('PROFILE_GENERATION_ENDPOINT')
CLOUDINARY_CLOUD_NAME = os.getenv('CLOUDINARY_CLOUD_NAME')
CLOUDINARY_API_KEY = os.getenv('CLOUDINARY_API_KEY')
CLOUDINARY_API_SECRET = os.getenv('CLOUDINARY_API_SECRET')
GCP_IMAGE_GENERATION_MODEL = os.getenv('GCP_IMAGE_GENERATION_MODEL')
GCP_SHOOT_GENERATION_MODEL = os.getenv('GCP_SHOOT_GENERATION_MODEL')
